"""derechos_consumidor

Revision ID: 677fcfabb86e
Revises: f5493c965dc2
Create Date: 2026-09-22 13:42:45.311625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677fcfabb86e'
down_revision: Union[str, Sequence[str], None] = 'f5493c965dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('fecha_baja', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_baja')
        batch_op.drop_column('activo')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
