"""add_creado_en_to_pedidos

Revision ID: f5493c965dc2
Revises: 1c01a485f049
Create Date: 2026-09-22 13:18:45.944739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5493c965dc2'
down_revision: Union[str, Sequence[str], None] = '1c01a485f049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('creado_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'creado_en')
    # ### end Alembic commands ###
